name: Compiler les fichiers LaTeX

on:
  push:
    paths:
      - '**.tex'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le repo
        uses: actions/checkout@v4

      - name: Compiler les fichiers LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "**/*.tex"
          continue_on_error: true
          pre_compile: |
            tlmgr install fouriernc tcolorbox pgf pgfplots bclogo awesomebox chemmacros tipfr tkz-base tkz-tab pstricks pst-labo qrcode numprint mdframed cancel

      - name: Pousser les PDF compilés
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add **/*.pdf
          git diff --cached --quiet || git commit -m "PDF compilés automatiquement"
          git push
